spring.application.name=${APPLICATION_NAME}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

custom.jwt.secret=${JWT_SECRET_KEY}
custom.jwt.expiration=${JWT_EXPIRATION_TIME}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLED}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SMTP_SSL_TRUST}
spring.mail.properties.mail.debug=${MAIL_SMTP_DEBUG}

file.upload-dir=${HR_STORAGE_DIR}
file.upload-folder=${HR_STORAGE_FOLDER}
file.intern.upload-dir=${INTERN_STORAGE_DIR}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=${GEMINI_AI_MODEL}