spring.application.name=${APPLICATION_NAME}

spring.datasource.url=${DATASOURCE_URL}
spring.security.user.name=${DATASOURCE_USERNAME}
spring.security.user.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

custom.jwt.secret=${JWT_SECRET_KEY}
custom.jwt.expiration=${JWT_EXPIRATION_TIME}